// Dados de demonstração — cópia de mobile/src/lib/seed.ts, carregada via POST /admin/demo.
/* eslint-disable */
type Estado = Record<string, any>

/** Centro aproximado usado pelo mapa quando não há nada cadastrado. */
export const CENTRO_PADRAO = { lat: -23.5015, lng: -46.6291 }

/**
 * Dados de demonstração — comunidade fictícia. Servem para que a aplicação
 * abra já com conteúdo navegável; podem ser zerados na tela de Ajustes.
 */
export const SEED: Estado = {
  usuario: 'Dona Marlene',
  rotas: [
    {
      id: 'rota_1',
      nome: 'Beco da Escada — acesso principal',
      tipo: 'Caminho a pé',
      condicao: 'Regular',
      iluminacao: false,
      acessivel: false,
      descricao:
        'Escadaria de 62 degraus ligando a rua de baixo ao topo. Sem corrimão no trecho final.',
      pontos: [
        { lat: -23.5008, lng: -46.6305 },
        { lat: -23.5013, lng: -46.6297 },
        { lat: -23.5019, lng: -46.6291 },
      ],
      autor: 'Dona Marlene',
      criadaEm: '2026-03-04T12:00:00.000Z',
      status: 'validada',
      confirmacoes: ['Seu Jorge', 'Rita'],
    },
    {
      id: 'rota_2',
      nome: 'Rota do caminhão de lixo',
      tipo: 'Coleta de lixo',
      condicao: 'Boa',
      iluminacao: true,
      acessivel: true,
      descricao: 'Passa terças, quintas e sábados por volta das 7h. Não entra no beco.',
      pontos: [
        { lat: -23.5002, lng: -46.6312 },
        { lat: -23.5006, lng: -46.6288 },
        { lat: -23.5017, lng: -46.6272 },
      ],
      autor: 'Seu Jorge',
      criadaEm: '2026-03-11T12:00:00.000Z',
      status: 'validada',
      confirmacoes: ['Dona Marlene'],
    },
    {
      id: 'rota_3',
      nome: 'Caminho da escola (crianças)',
      tipo: 'Rota escolar',
      condicao: 'Ruim',
      iluminacao: false,
      acessivel: false,
      descricao:
        'Trecho de terra que alaga quando chove forte. As crianças desviam pelo terreno do lado.',
      pontos: [
        { lat: -23.5024, lng: -46.6301 },
        { lat: -23.5028, lng: -46.6289 },
        { lat: -23.5023, lng: -46.6278 },
      ],
      autor: 'Rita',
      criadaEm: '2026-04-02T12:00:00.000Z',
      status: 'pendente',
      confirmacoes: [],
    },
  ],
  alertas: [
    {
      id: 'alerta_1',
      tipo: 'Sem iluminação',
      gravidade: 'Alta',
      descricao: 'Três postes queimados na subida do beco. Escuro total depois das 19h.',
      ponto: { lat: -23.5014, lng: -46.6295 },
      autor: 'Dona Marlene',
      criadoEm: '2026-05-19T12:00:00.000Z',
      resolvido: false,
      confirmacoes: ['Rita', 'Seu Jorge'],
    },
    {
      id: 'alerta_2',
      tipo: 'Alagamento',
      gravidade: 'Média',
      descricao: 'Boca de lobo entupida, alaga a esquina inteira em chuva de verão.',
      ponto: { lat: -23.5026, lng: -46.6285 },
      autor: 'Rita',
      criadoEm: '2026-06-01T12:00:00.000Z',
      resolvido: false,
      confirmacoes: [],
    },
  ],
  comercios: [
    {
      id: 'com_1',
      nome: 'Mercadinho do Zé',
      responsavel: 'José Ribeiro',
      categoria: 'Mercearia / Mercado',
      descricao: 'Mercearia de esquina, fiado para clientes antigos.',
      telefone: '(11) 98888-1122',
      whatsapp: true,
      endereco: 'Rua das Acácias, 45',
      horario: 'Seg a sáb, 7h às 20h',
      formalizado: true,
      cnpjMei: '12.345.678/0001-90',
      aceitaFiado: true,
      entrega: true,
      ponto: { lat: -23.5011, lng: -46.6299 },
      tags: ['gás', 'água', 'hortifruti'],
      autor: '',
      criadoEm: '2026-02-10T12:00:00.000Z',
    },
    {
      id: 'com_2',
      nome: 'Salão da Cida',
      responsavel: 'Aparecida Nunes',
      categoria: 'Beleza',
      descricao: 'Cabelo, unha e sobrancelha. Atende com hora marcada.',
      telefone: '(11) 97777-3344',
      whatsapp: true,
      endereco: 'Travessa São Pedro, 12',
      horario: 'Ter a sáb, 9h às 18h',
      formalizado: false,
      cnpjMei: '',
      aceitaFiado: false,
      entrega: false,
      ponto: { lat: -23.5021, lng: -46.6283 },
      tags: ['cabelo', 'manicure'],
      autor: '',
      criadoEm: '2026-02-22T12:00:00.000Z',
    },
  ],
  freelancers: [
    {
      id: 'free_1',
      nome: 'Marcos Alves',
      profissao: 'Eletricista',
      descricao: 'Instalação e reparo residencial. 12 anos de experiência.',
      telefone: '(11) 96666-5544',
      whatsapp: true,
      habilidades: ['instalação elétrica', 'quadro de luz', 'chuveiro'],
      disponibilidade: ['Tarde', 'Fim de semana'],
      precoMin: 80,
      precoMax: 250,
      unidadePreco: 'serviço',
      atendeDomicilio: true,
      temTransporte: true,
      bairro: 'Vila Esperança',
      autor: '',
      criadoEm: '2026-03-01T12:00:00.000Z',
    },
    {
      id: 'free_2',
      nome: 'Juliana Prado',
      profissao: 'Costureira',
      descricao: 'Ajustes, barras e consertos em geral. Uniformes escolares.',
      telefone: '(11) 95555-2211',
      whatsapp: true,
      habilidades: ['ajuste', 'barra', 'uniforme'],
      disponibilidade: ['Manhã', 'Tarde'],
      precoMin: 15,
      precoMax: 90,
      unidadePreco: 'serviço',
      atendeDomicilio: false,
      temTransporte: false,
      bairro: 'Vila Esperança',
      autor: '',
      criadoEm: '2026-03-18T12:00:00.000Z',
    },
  ],
  casas: [
    {
      id: 'casa_1',
      apelido: 'Casa da Dona Marlene',
      endereco: 'Beco da Escada, 8',
      quadra: '4',
      lote: '12',
      tipoConstrucao: 'Alvenaria',
      situacao: 'Própria',
      comodos: 4,
      aguaEncanada: true,
      esgoto: false,
      energiaEletrica: true,
      coletaLixo: false,
      riscos: ['Deslizamento'],
      ponto: { lat: -23.5016, lng: -46.6293 },
      observacoes: 'Muro de arrimo com rachadura no fundo do lote.',
      criadaEm: '2026-01-15T12:00:00.000Z',
    },
    {
      id: 'casa_2',
      apelido: 'Casa dos Silva',
      endereco: 'Rua das Acácias, 102',
      quadra: '5',
      lote: '3',
      tipoConstrucao: 'Mista',
      situacao: 'Alugada',
      comodos: 2,
      aguaEncanada: true,
      esgoto: true,
      energiaEletrica: true,
      coletaLixo: true,
      riscos: ['Alagamento'],
      ponto: { lat: -23.5027, lng: -46.6287 },
      observacoes: '',
      criadaEm: '2026-01-20T12:00:00.000Z',
    },
  ],
  familias: [
    {
      id: 'fam_1',
      nomeFamilia: 'Família Marlene Souza',
      casaId: 'casa_1',
      responsavel: 'Marlene Souza',
      telefone: '(11) 98888-0001',
      nis: '123.45678.90-1',
      rendaMensal: 1600,
      beneficios: ['Tarifa Social de Energia'],
      membros: [
        {
          id: 'mem_1',
          nome: 'Marlene Souza',
          nascimento: '1962-07-14',
          parentesco: 'Responsável',
          escolaridade: 'Fundamental incompleto',
          estuda: false,
          trabalha: true,
          pcd: false,
          doencaCronica: true,
          gestante: false,
        },
        {
          id: 'mem_2',
          nome: 'Pedro Souza',
          nascimento: '2014-02-09',
          parentesco: 'Neto(a)',
          escolaridade: 'Fundamental incompleto',
          estuda: true,
          trabalha: false,
          pcd: false,
          doencaCronica: false,
          gestante: false,
        },
      ],
      observacoes: 'Acompanhada pela UBS Vila Esperança.',
      criadaEm: '2026-01-15T12:00:00.000Z',
    },
    {
      id: 'fam_2',
      nomeFamilia: 'Família Silva',
      casaId: 'casa_2',
      responsavel: 'Rita Silva',
      telefone: '(11) 97777-0002',
      nis: '',
      rendaMensal: 900,
      beneficios: ['Bolsa Família'],
      membros: [
        {
          id: 'mem_3',
          nome: 'Rita Silva',
          nascimento: '1994-11-30',
          parentesco: 'Responsável',
          escolaridade: 'Médio completo',
          estuda: false,
          trabalha: false,
          pcd: false,
          doencaCronica: false,
          gestante: true,
        },
        {
          id: 'mem_4',
          nome: 'Lucas Silva',
          nascimento: '2021-05-02',
          parentesco: 'Filho(a)',
          escolaridade: 'Não alfabetizado',
          estuda: false,
          trabalha: false,
          pcd: false,
          doencaCronica: false,
          gestante: false,
        },
        {
          id: 'mem_5',
          nome: 'Ana Silva',
          nascimento: '2012-09-21',
          parentesco: 'Filho(a)',
          escolaridade: 'Fundamental incompleto',
          estuda: true,
          trabalha: false,
          pcd: true,
          doencaCronica: false,
          gestante: false,
        },
      ],
      observacoes: 'Precisa de encaminhamento para o CRAS.',
      criadaEm: '2026-01-20T12:00:00.000Z',
    },
  ],
}
